RF_DETR_MODEL_CONFIG = {
    "RFDETRNano": {
        "backbone_size": "small",
        "hidden_dim": 256,
        "backbone_hidden_size": 384,
        "backbone_num_heads": 6,
        "backbone_num_layers": 12,
        "backbone_mlp_ratio": 4,
        "backbone_use_swiglu": False,
        "num_register_tokens": 0,
        "out_feature_indexes": [3, 6, 9, 12],
        "patch_size": 16,
        "num_windows": 2,
        "positional_encoding_size": 24,
        "resolution": 384,
        "dec_layers": 2,
        "sa_nheads": 8,
        "ca_nheads": 16,
        "dec_n_points": 2,
        "num_queries": 300,
        "num_classes": 91,
        "two_stage": True,
        "bbox_reparam": True,
        "lite_refpoint_refine": True,
        "group_detr": 13,
        "dim_feedforward": 2048,
    },
    "RFDETRSmall": {
        "backbone_size": "small",
        "hidden_dim": 256,
        "backbone_hidden_size": 384,
        "backbone_num_heads": 6,
        "backbone_num_layers": 12,
        "backbone_mlp_ratio": 4,
        "backbone_use_swiglu": False,
        "num_register_tokens": 0,
        "out_feature_indexes": [3, 6, 9, 12],
        "patch_size": 16,
        "num_windows": 2,
        "positional_encoding_size": 32,
        "resolution": 512,
        "dec_layers": 3,
        "sa_nheads": 8,
        "ca_nheads": 16,
        "dec_n_points": 2,
        "num_queries": 300,
        "num_classes": 91,
        "two_stage": True,
        "bbox_reparam": True,
        "lite_refpoint_refine": True,
        "group_detr": 13,
        "dim_feedforward": 2048,
    },
    "RFDETRMedium": {
        "backbone_size": "small",
        "hidden_dim": 256,
        "backbone_hidden_size": 384,
        "backbone_num_heads": 6,
        "backbone_num_layers": 12,
        "backbone_mlp_ratio": 4,
        "backbone_use_swiglu": False,
        "num_register_tokens": 0,
        "out_feature_indexes": [3, 6, 9, 12],
        "patch_size": 16,
        "num_windows": 2,
        "positional_encoding_size": 36,
        "resolution": 576,
        "dec_layers": 4,
        "sa_nheads": 8,
        "ca_nheads": 16,
        "dec_n_points": 2,
        "num_queries": 300,
        "num_classes": 91,
        "two_stage": True,
        "bbox_reparam": True,
        "lite_refpoint_refine": True,
        "group_detr": 13,
        "dim_feedforward": 2048,
    },
    "RFDETRBase": {
        "backbone_size": "small",
        "hidden_dim": 256,
        "backbone_hidden_size": 384,
        "backbone_num_heads": 6,
        "backbone_num_layers": 12,
        "backbone_mlp_ratio": 4,
        "backbone_use_swiglu": False,
        "num_register_tokens": 0,
        "out_feature_indexes": [2, 5, 8, 11],
        "patch_size": 14,
        "num_windows": 4,
        "positional_encoding_size": 37,
        "resolution": 560,
        "dec_layers": 3,
        "sa_nheads": 8,
        "ca_nheads": 16,
        "dec_n_points": 2,
        "num_queries": 300,
        "num_classes": 91,
        "two_stage": True,
        "bbox_reparam": True,
        "lite_refpoint_refine": True,
        "group_detr": 13,
        "dim_feedforward": 2048,
    },
    "RFDETRLarge": {
        "backbone_size": "small",
        "hidden_dim": 256,
        "backbone_hidden_size": 384,
        "backbone_num_heads": 6,
        "backbone_num_layers": 12,
        "backbone_mlp_ratio": 4,
        "backbone_use_swiglu": False,
        "num_register_tokens": 0,
        "out_feature_indexes": [3, 6, 9, 12],
        "patch_size": 16,
        "num_windows": 2,
        "positional_encoding_size": 44,
        "resolution": 704,
        "dec_layers": 4,
        "sa_nheads": 8,
        "ca_nheads": 16,
        "dec_n_points": 2,
        "num_queries": 300,
        "num_classes": 91,
        "two_stage": True,
        "bbox_reparam": True,
        "lite_refpoint_refine": True,
        "group_detr": 13,
        "dim_feedforward": 2048,
    },
}

RF_DETR_WEIGHTS_CONFIG = {
    "RFDETRNano": {
        "coco": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/rf-detr/rf_detr_nano_coco.weights.h5",
        },
    },
    "RFDETRSmall": {
        "coco": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/rf-detr/rf_detr_small_coco.weights.h5",
        },
    },
    "RFDETRMedium": {
        "coco": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/rf-detr/rf_detr_medium_coco.weights.h5",
        },
    },
    "RFDETRBase": {
        "coco": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/rf-detr/rf_detr_base_coco.weights.h5",
        },
    },
    "RFDETRLarge": {
        "coco": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/rf-detr/rf_detr_large_coco.weights.h5",
        },
    },
}
