[tool.ruff.lint]
ignore = ["C901", "E501", "E741", "F402", "F823"]
select = ["C", "E", "F", "I", "W"]

# Ignore specific linting errors for ALL __init__.py files
[tool.ruff.lint.per-file-ignores]
"**/*/____init__.py" = ["E402", "F401", "F403", "F811"]