SAM_MODEL_CONFIG = {
    "SAM_ViT_Base": {
        "vision_hidden_size": 768,
        "vision_num_hidden_layers": 12,
        "vision_num_attention_heads": 12,
        "vision_mlp_dim": 3072,
        "vision_output_channels": 256,
        "vision_patch_size": 16,
        "vision_image_size": 1024,
        "vision_window_size": 14,
        "vision_global_attn_indexes": [2, 5, 8, 11],
        "vision_layer_norm_eps": 1e-6,
        "vision_qkv_bias": True,
        "vision_use_abs_pos": True,
        "vision_use_rel_pos": True,
        "mask_decoder_hidden_size": 256,
        "mask_decoder_num_hidden_layers": 2,
        "mask_decoder_num_attention_heads": 8,
        "mask_decoder_mlp_dim": 2048,
        "mask_decoder_iou_head_depth": 3,
        "mask_decoder_iou_head_hidden_dim": 256,
        "prompt_encoder_hidden_size": 256,
        "prompt_encoder_mask_input_channels": 16,
        "prompt_encoder_num_point_embeddings": 4,
    },
    "SAM_ViT_Large": {
        "vision_hidden_size": 1024,
        "vision_num_hidden_layers": 24,
        "vision_num_attention_heads": 16,
        "vision_mlp_dim": 4096,
        "vision_output_channels": 256,
        "vision_patch_size": 16,
        "vision_image_size": 1024,
        "vision_window_size": 14,
        "vision_global_attn_indexes": [5, 11, 17, 23],
        "vision_layer_norm_eps": 1e-6,
        "vision_qkv_bias": True,
        "vision_use_abs_pos": True,
        "vision_use_rel_pos": True,
        "mask_decoder_hidden_size": 256,
        "mask_decoder_num_hidden_layers": 2,
        "mask_decoder_num_attention_heads": 8,
        "mask_decoder_mlp_dim": 2048,
        "mask_decoder_iou_head_depth": 3,
        "mask_decoder_iou_head_hidden_dim": 256,
        "prompt_encoder_hidden_size": 256,
        "prompt_encoder_mask_input_channels": 16,
        "prompt_encoder_num_point_embeddings": 4,
    },
    "SAM_ViT_Huge": {
        "vision_hidden_size": 1280,
        "vision_num_hidden_layers": 32,
        "vision_num_attention_heads": 16,
        "vision_mlp_dim": 5120,
        "vision_output_channels": 256,
        "vision_patch_size": 16,
        "vision_image_size": 1024,
        "vision_window_size": 14,
        "vision_global_attn_indexes": [7, 15, 23, 31],
        "vision_layer_norm_eps": 1e-6,
        "vision_qkv_bias": True,
        "vision_use_abs_pos": True,
        "vision_use_rel_pos": True,
        "mask_decoder_hidden_size": 256,
        "mask_decoder_num_hidden_layers": 2,
        "mask_decoder_num_attention_heads": 8,
        "mask_decoder_mlp_dim": 2048,
        "mask_decoder_iou_head_depth": 3,
        "mask_decoder_iou_head_hidden_dim": 256,
        "prompt_encoder_hidden_size": 256,
        "prompt_encoder_mask_input_channels": 16,
        "prompt_encoder_num_point_embeddings": 4,
    },
}

SAM_WEIGHTS_CONFIG = {
    "SAM_ViT_Base": {
        "sa1b": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/SAM/sam_vit_base.weights.h5",
        },
    },
    "SAM_ViT_Large": {
        "sa1b": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/SAM/sam_vit_large.weights.h5",
        },
    },
    "SAM_ViT_Huge": {
        "sa1b": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/SAM/sam_vit_huge.weights.h5",
        },
    },
}
