WHISPER_MODEL_CONFIG = {
    "WhisperTiny": {
        "d_model": 384,
        "encoder_layers": 4,
        "encoder_attention_heads": 6,
        "encoder_ffn_dim": 1536,
        "decoder_layers": 4,
        "decoder_attention_heads": 6,
        "decoder_ffn_dim": 1536,
        "vocab_size": 51865,
        "max_source_positions": 1500,
        "max_target_positions": 448,
        "num_mel_bins": 80,
    },
    "WhisperBase": {
        "d_model": 512,
        "encoder_layers": 6,
        "encoder_attention_heads": 8,
        "encoder_ffn_dim": 2048,
        "decoder_layers": 6,
        "decoder_attention_heads": 8,
        "decoder_ffn_dim": 2048,
        "vocab_size": 51865,
        "max_source_positions": 1500,
        "max_target_positions": 448,
        "num_mel_bins": 80,
    },
    "WhisperSmall": {
        "d_model": 768,
        "encoder_layers": 12,
        "encoder_attention_heads": 12,
        "encoder_ffn_dim": 3072,
        "decoder_layers": 12,
        "decoder_attention_heads": 12,
        "decoder_ffn_dim": 3072,
        "vocab_size": 51865,
        "max_source_positions": 1500,
        "max_target_positions": 448,
        "num_mel_bins": 80,
    },
    "WhisperMedium": {
        "d_model": 1024,
        "encoder_layers": 24,
        "encoder_attention_heads": 16,
        "encoder_ffn_dim": 4096,
        "decoder_layers": 24,
        "decoder_attention_heads": 16,
        "decoder_ffn_dim": 4096,
        "vocab_size": 51865,
        "max_source_positions": 1500,
        "max_target_positions": 448,
        "num_mel_bins": 80,
    },
    "WhisperLarge": {
        "d_model": 1280,
        "encoder_layers": 32,
        "encoder_attention_heads": 20,
        "encoder_ffn_dim": 5120,
        "decoder_layers": 32,
        "decoder_attention_heads": 20,
        "decoder_ffn_dim": 5120,
        "vocab_size": 51865,
        "max_source_positions": 1500,
        "max_target_positions": 448,
        "num_mel_bins": 80,
    },
    "WhisperLargeV2": {
        "d_model": 1280,
        "encoder_layers": 32,
        "encoder_attention_heads": 20,
        "encoder_ffn_dim": 5120,
        "decoder_layers": 32,
        "decoder_attention_heads": 20,
        "decoder_ffn_dim": 5120,
        "vocab_size": 51865,
        "max_source_positions": 1500,
        "max_target_positions": 448,
        "num_mel_bins": 80,
    },
    "WhisperLargeV3": {
        "d_model": 1280,
        "encoder_layers": 32,
        "encoder_attention_heads": 20,
        "encoder_ffn_dim": 5120,
        "decoder_layers": 32,
        "decoder_attention_heads": 20,
        "decoder_ffn_dim": 5120,
        "vocab_size": 51866,
        "max_source_positions": 1500,
        "max_target_positions": 448,
        "num_mel_bins": 128,
    },
    "WhisperLargeV3Turbo": {
        "d_model": 1280,
        "encoder_layers": 32,
        "encoder_attention_heads": 20,
        "encoder_ffn_dim": 5120,
        "decoder_layers": 4,
        "decoder_attention_heads": 20,
        "decoder_ffn_dim": 5120,
        "vocab_size": 51866,
        "max_source_positions": 1500,
        "max_target_positions": 448,
        "num_mel_bins": 128,
    },
}


# OpenAI Whisper's hard-coded logits processor lists (see
# `whisper/decoding.py` and HF's `GenerationConfig`).
WHISPER_SUPPRESS_TOKENS = [
    1,
    2,
    7,
    8,
    9,
    10,
    14,
    25,
    26,
    27,
    28,
    29,
    31,
    58,
    59,
    60,
    61,
    62,
    63,
    90,
    91,
    92,
    93,
    359,
    503,
    522,
    542,
    873,
    893,
    902,
    918,
    922,
    931,
    1350,
    1853,
    1982,
    2460,
    2627,
    3246,
    3253,
    3268,
    3536,
    3846,
    3961,
    4183,
    4667,
    6585,
    6647,
    7273,
    9061,
    9383,
    10428,
    10929,
    11938,
    12033,
    12331,
    12562,
    13793,
    14157,
    14635,
    15265,
    15618,
    16553,
    16604,
    18362,
    18956,
    20075,
    21675,
    22520,
    26130,
    26161,
    26435,
    28279,
    29464,
    31650,
    32302,
    32470,
    36865,
    42863,
    47425,
    49870,
    50254,
    50258,
    50360,
    50361,
    50362,
]
WHISPER_BEGIN_SUPPRESS_TOKENS = [220, 50257]


# Tokenizer files uploaded to the kmodels "whisper" release tag.
# v1  -> tiny / base / small / medium / large / large-v2   (51865 vocab)
# v3  -> large-v3 / large-v3-turbo                          (51866 vocab)
WHISPER_TOKENIZER_FILES = {
    "v1": {
        "vocab": "https://github.com/IMvision12/keras-models/releases/download/whisper/whisper_vocab.json",
        "merges": "https://github.com/IMvision12/keras-models/releases/download/whisper/whisper_merges.txt",
        "added_tokens": "https://github.com/IMvision12/keras-models/releases/download/whisper/whisper_added_tokens.json",
    },
    "v3": {
        "vocab": "https://github.com/IMvision12/keras-models/releases/download/whisper/whisper_vocab_v3.json",
        "merges": "https://github.com/IMvision12/keras-models/releases/download/whisper/whisper_merges_v3.txt",
        "added_tokens": "https://github.com/IMvision12/keras-models/releases/download/whisper/whisper_added_tokens_v3.json",
    },
}


WHISPER_WEIGHTS_CONFIG = {
    "WhisperTiny": {
        "openai": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/whisper/whispertiny_openai.weights.h5",
        },
    },
    "WhisperBase": {
        "openai": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/whisper/whisperbase_openai.weights.h5",
        },
    },
    "WhisperSmall": {
        "openai": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/whisper/whispersmall_openai.weights.h5",
        },
    },
    "WhisperMedium": {
        "openai": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/whisper/whispermedium_openai.weights.json",
        },
    },
    "WhisperLarge": {
        "openai": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/whisper/whisperlarge_openai.weights.json",
        },
    },
    "WhisperLargeV2": {
        "openai": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/whisper/whisperlargev2_openai.weights.json",
        },
    },
    "WhisperLargeV3": {
        "openai": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/whisper/whisperlargev3_openai.weights.json",
        },
    },
    "WhisperLargeV3Turbo": {
        "openai": {
            "url": "https://github.com/IMvision12/keras-models/releases/download/whisper/whisperlargev3turbo_openai.weights.json",
        },
    },
}
