"""Canonical label vocabularies for kmodels image-processor post-processing.

Single source of truth for class-name lists used by detection and
segmentation post-processors. Tuples (immutable, hashable) — do not
mutate; copy first if you need a mutable list.
"""

# COCO with N/A placeholders (detr / rf_detr) — 91 entries.
COCO_91_CLASSES = (
    "N/A",
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "N/A",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "N/A",
    "backpack",
    "umbrella",
    "N/A",
    "N/A",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "N/A",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "N/A",
    "dining table",
    "N/A",
    "N/A",
    "toilet",
    "N/A",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "N/A",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
)

# COCO populated only (dfine / rt_detr / rt_detr_v2) — 80 entries.
COCO_80_CLASSES = (
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
)

# COCO panoptic (eomt) — 80 things + 53 stuff = 133 entries.
COCO_PANOPTIC_133_CLASSES = (
    "things: person",
    "things: bicycle",
    "things: car",
    "things: motorcycle",
    "things: airplane",
    "things: bus",
    "things: train",
    "things: truck",
    "things: boat",
    "things: traffic light",
    "things: fire hydrant",
    "things: stop sign",
    "things: parking meter",
    "things: bench",
    "things: bird",
    "things: cat",
    "things: dog",
    "things: horse",
    "things: sheep",
    "things: cow",
    "things: elephant",
    "things: bear",
    "things: zebra",
    "things: giraffe",
    "things: backpack",
    "things: umbrella",
    "things: handbag",
    "things: tie",
    "things: suitcase",
    "things: frisbee",
    "things: skis",
    "things: snowboard",
    "things: sports ball",
    "things: kite",
    "things: baseball bat",
    "things: baseball glove",
    "things: skateboard",
    "things: surfboard",
    "things: tennis racket",
    "things: bottle",
    "things: wine glass",
    "things: cup",
    "things: fork",
    "things: knife",
    "things: spoon",
    "things: bowl",
    "things: banana",
    "things: apple",
    "things: sandwich",
    "things: orange",
    "things: broccoli",
    "things: carrot",
    "things: hot dog",
    "things: pizza",
    "things: donut",
    "things: cake",
    "things: chair",
    "things: couch",
    "things: potted plant",
    "things: bed",
    "things: dining table",
    "things: toilet",
    "things: tv",
    "things: laptop",
    "things: mouse",
    "things: remote",
    "things: keyboard",
    "things: cell phone",
    "things: microwave",
    "things: oven",
    "things: toaster",
    "things: sink",
    "things: refrigerator",
    "things: book",
    "things: clock",
    "things: vase",
    "things: scissors",
    "things: teddy bear",
    "things: hair drier",
    "things: toothbrush",
    "stuff: banner",
    "stuff: blanket",
    "stuff: bridge",
    "stuff: cardboard",
    "stuff: counter",
    "stuff: curtain",
    "stuff: door-stuff",
    "stuff: floor-wood",
    "stuff: flower",
    "stuff: fruit",
    "stuff: gravel",
    "stuff: house",
    "stuff: light",
    "stuff: mirror-stuff",
    "stuff: net",
    "stuff: pillow",
    "stuff: platform",
    "stuff: playingfield",
    "stuff: railroad",
    "stuff: river",
    "stuff: road",
    "stuff: roof",
    "stuff: sand",
    "stuff: sea",
    "stuff: shelf",
    "stuff: snow",
    "stuff: stairs",
    "stuff: tent",
    "stuff: towel",
    "stuff: wall-brick",
    "stuff: wall-concrete",
    "stuff: wall-other",
    "stuff: wall-stone",
    "stuff: wall-tile",
    "stuff: wall-wood",
    "stuff: water-other",
    "stuff: window-blind",
    "stuff: window-other",
    "stuff: tree-merged",
    "stuff: fence-merged",
    "stuff: ceiling-merged",
    "stuff: sky-other-merged",
    "stuff: floor-other-merged",
    "stuff: pavement-merged",
    "stuff: mountain-merged",
    "stuff: grass-merged",
    "stuff: dirt-merged",
    "stuff: paper-merged",
    "stuff: food-other-merged",
    "stuff: building-other-merged",
    "stuff: rock-merged",
    "stuff: wall-other-merged",
    "stuff: rug-merged",
)

# Index ranges into COCO_PANOPTIC_133_CLASSES.
COCO_PANOPTIC_THING_IDS = tuple(range(80))
COCO_PANOPTIC_STUFF_IDS = tuple(range(80, 133))

# ADE20K semantic (segformer) — 150 entries.
ADE20K_150_CLASSES = (
    "wall",
    "building",
    "sky",
    "floor",
    "tree",
    "ceiling",
    "road",
    "bed",
    "windowpane",
    "grass",
    "cabinet",
    "sidewalk",
    "person",
    "earth",
    "door",
    "table",
    "mountain",
    "plant",
    "curtain",
    "chair",
    "car",
    "water",
    "painting",
    "sofa",
    "shelf",
    "house",
    "sea",
    "mirror",
    "rug",
    "field",
    "armchair",
    "seat",
    "fence",
    "desk",
    "rock",
    "wardrobe",
    "lamp",
    "bathtub",
    "railing",
    "cushion",
    "base",
    "box",
    "column",
    "signboard",
    "chest of drawers",
    "counter",
    "sand",
    "sink",
    "skyscraper",
    "fireplace",
    "refrigerator",
    "grandstand",
    "path",
    "stairs",
    "runway",
    "case",
    "pool table",
    "pillow",
    "screen door",
    "stairway",
    "river",
    "bridge",
    "bookcase",
    "blind",
    "coffee table",
    "toilet",
    "flower",
    "book",
    "hill",
    "bench",
    "countertop",
    "stove",
    "palm",
    "kitchen island",
    "computer",
    "swivel chair",
    "boat",
    "bar",
    "arcade machine",
    "hovel",
    "bus",
    "towel",
    "light",
    "truck",
    "tower",
    "chandelier",
    "awning",
    "streetlight",
    "booth",
    "television",
    "airplane",
    "dirt track",
    "apparel",
    "pole",
    "land",
    "bannister",
    "escalator",
    "ottoman",
    "bottle",
    "buffet",
    "poster",
    "stage",
    "van",
    "ship",
    "fountain",
    "conveyer belt",
    "canopy",
    "washer",
    "plaything",
    "swimming pool",
    "stool",
    "barrel",
    "basket",
    "waterfall",
    "tent",
    "bag",
    "minibike",
    "cradle",
    "oven",
    "ball",
    "food",
    "step",
    "tank",
    "trade name",
    "microwave",
    "pot",
    "animal",
    "bicycle",
    "lake",
    "dishwasher",
    "screen",
    "blanket",
    "sculpture",
    "hood",
    "sconce",
    "vase",
    "traffic light",
    "tray",
    "ashcan",
    "fan",
    "pier",
    "crt screen",
    "plate",
    "monitor",
    "bulletin board",
    "shower",
    "radiator",
    "glass",
    "clock",
    "flag",
)

# Cityscapes semantic (segformer) — 19 entries.
CITYSCAPES_19_CLASSES = (
    "road",
    "sidewalk",
    "building",
    "wall",
    "fence",
    "pole",
    "traffic light",
    "traffic sign",
    "vegetation",
    "terrain",
    "sky",
    "person",
    "rider",
    "car",
    "truck",
    "bus",
    "train",
    "motorcycle",
    "bicycle",
)

# Pascal VOC (deeplabv3) — 21 entries with background.
PASCAL_VOC_CLASSES = (
    "background",
    "aeroplane",
    "bicycle",
    "bird",
    "boat",
    "bottle",
    "bus",
    "car",
    "cat",
    "chair",
    "cow",
    "dining table",
    "dog",
    "horse",
    "motorbike",
    "person",
    "potted plant",
    "sheep",
    "sofa",
    "train",
    "tv/monitor",
)
